# Generated by Django 4.2.1 on 2023-05-28 03:34

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='No Image', upload_to='profiles'),
            preserve_default=False,
        ),
    ]
