# Generated by Django 4.2.1 on 2023-05-24 10:16

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='No Image', upload_to=''),
            preserve_default=False,
        ),
    ]
