# Generated by Django 4.2.1 on 2023-05-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 24)),
            preserve_default=False,
        ),
    ]
